###########################################################################
##  Copyright 2018 Vincent Camus all rights reserved                     ##
##                                                                       ##
##  Project: Carry Cut-Back Adder (CCBA) Source Code                     ##
##  Authors: Vincent Camus (EPFL-ICLAB), vincent.camus@epfl.ch           ##
##  License: BSD-2-Clause                                                ##
##                                                                       ##
##  File: sim_gate_modelsim.tcl                                          ##
##  Description: script for gate-level timing verification of the        ##
##  synthetized CCBA with MentorGraphics Modelsim/Questa, runs the       ##
##  tb_adder32_gate testbench comparing the synthetized netlist with     ##
##  its expected behavior, shows the error count/assertions on screen    ##
##  and generates a results.txt file with listing of inconsistencies     ##
##  Usage: vsim -do sim_gate_modelsim.tcl ('-c' for command-line mode)   ##
##                                                                       ##
##  Version: 1.0 (initial version)                                       ##
##                                                                       ##
##  Notes: overwrites the DELAY value in the tb_adder32_gate.vhd file    ##
###########################################################################


################### PARAMETERS ###################

# delay constraint (do not hesitate to modify to check the level of the first errors)
set DELAY      0.5

# HDL paths
set RTL_PATH   ../rtl
set GATE_PATH  ../syn
set BENCH_PATH ../bench

# standard-cell library
set LIB_FILE   ../lib/NangateOpenCellLibrary_PDKv1_3_v2010_12/verilog/NangateOpenCellLibrary.v

###### COMPILE STD-CELLS & GATE-LEVEL SOURCE #####

vlib gate
vmap gate gate

# compile library
vlog -work gate -quiet $LIB_FILE

# using the gate-level adder32 generated by the synthesis script
vlog -work gate $GATE_PATH/adder32.v


############### COMPILE RTL SOURCE ###############

vlib work
vmap work work

vcom -work work $RTL_PATH/ccba_pkg.vhd
vcom -work work $RTL_PATH/ccba.vhd
vcom -work work $RTL_PATH/ccba_regular.vhd

# the RTL wrapper will be compared to the gate-level netlist
# hence, do not modify the wrapper after synthesis
vcom -work work $RTL_PATH/wrapper_ccba_regular_adder32.vhd

vcom -work work $BENCH_PATH/tb_adder32_gate.vhd

################### SIMULATION ###################

# a file named "results.txt" will be created listing the errors
vsim tb_adder32_gate -t ps \
	-sdfmax uut_gate=$GATE_PATH/adder32.sdf \
	-sdfnowarn -sdfnoerror -noglitch \
	-g DELAY=${DELAY}ns
	
add wave *
run -all
quit
